services:
  client:
    build: ./client
    ports:
      - "8080:4201"
    depends_on:
      - api
    env_file:
      - ./client/.env.docker
    networks:
      - blog_default
  api:
    build: ./api
    ports:
      - "3010:3100"
    depends_on:
      - db
    env_file:
      - ./api/.env.docker
    networks:
      - blog_default

  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5433:5432"
    networks:
      - blog_default

networks:
  blog_default:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16