services:
  client:
    build: ./client
    ports:
      - "8080:4201"
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - "3010:3100"
    networks:
      blog_default:
        ipv4_address: 172.19.0.10

  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

networks:
  blog_default:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
