export default () => ({
  port: process.env.PORT || 3100,
  host: process.env.HOST,
  googleClientId: process.env.GOOGLE_CLIENT_ID,
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
  googleCallBackPath: process.env.GOOGLE_CALLBACK_PATH,
  googleScopes: process.env.GOOGLE_SCOPES.split(','),
  facebookAppId: process.env.FACEBOOK_APP_ID,
  facebookAppSecret: process.env.FACEBOOK_APP_SECRET,
  facebookCallBackPath: process.env.FACEBOOK_CALLBACK_PATH,
  facebookScopes: process.env.FACEBOOK_SCOPES.split(','),
  token: process.env.TOKEN,
  tokenExpiry: process.env.TOKEN_EXPIRY,
  refreshToken: process.env.REFRESH_TOKEN,
  refreshTokenExpiry: process.env.REFRESH_TOKEN_EXPIRY,
  dbType: process.env.DB_TYPE,
  dbHost: process.env.DB_HOST,
  dbPort: Number(process.env.DB_PORT),
  dbUserName: process.env.DB_USERNAME,
  dbPassword: process.env.DB_PASSWORD,
  dbDefault: process.env.DB_DEFAULT_DATABASE,
  dbName: process.env.DB_DATABASE,
  dbSync: process.env.DB_SYNC === "true",
  dbMigrationsRun: process.env.DB_MIGRATIONS_RUN === "true",
  dbMinPool: Number(process.env.DB_MIN_POOL),
  dbMaxPool: Number(process.env.DB_MAX_POOL),
  dbIdleTimeout: Number(process.env.DB_IDLE_TIMEOUT),
  allowedOrigins: process.env.ALLOWED_ORIGINS.split(',')
});
