apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: ecr-registry
      containers:
        - name: api
          image: ${API_IMAGE}
          ports:
            - containerPort: 3010
          envFrom:
            - secretRef:
                name: api-env
          imagePullPolicy: Always

