apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      imagePullSecrets:
        - name: ecr-registry
      containers:
        - name: client
          image: ${CLIENT_IMAGE}
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: client-env

